### ISSUE TITLE
Error compiling on windows 10

### ISSUE THREAD

**Issue by QuanticDisaster** [sadeepj/crfasrnn_pytorch#8]
Hello @sadeepj 

I am encountering a problem to compile the C++ code parts on windows 10. While it works fine on Linux, wether it be with the newest torch versions or older ones, I am unable to make it work on windows 10 and am encoutnering the following error at compilation  
 
```python
running install
running bdist_egg
running egg_info
writing permuto_cpp.egg-info\PKG-INFO
writing dependency_links to permuto_cpp.egg-info\dependency_links.txt
writing top-level names to permuto_cpp.egg-info\top_level.txt
reading manifest file 'permuto_cpp.egg-info\SOURCES.txt'
writing manifest file 'permuto_cpp.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xa2 in position 24: invalid start byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'permuto_cpp' extension
Emitting ninja build file C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\TH -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\THC -IC:\Users\group\anaconda3\envs\crfrnn\include -IC:\Users\group\anaconda3\envs\crfrnn\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp /FoC:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\build\temp.win-amd64-3.7\Release\permutohedral.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=permuto_cpp -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/group/Downloads/test_compil/crfasrnn_pytorch/crfasrnn/build/temp.win-amd64-3.7/Release/permutohedral.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\TH -IC:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\include\THC -IC:\Users\group\anaconda3\envs\crfrnn\include -IC:\Users\group\anaconda3\envs\crfrnn\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp /FoC:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\build\temp.win-amd64-3.7\Release\permutohedral.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=permuto_cpp -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
Nota: inclusión del archivo: C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.h
Nota: inclusión del archivo:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstdlib
Nota: inclusión del archivo:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\sal.h
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\concurrencysal.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vadefs.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h
Nota: inclusión del archivo:   C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\math.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_math.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt.h
Nota: inclusión del archivo:   C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdlib.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_malloc.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_search.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wstdlib.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\limits.h
Nota: inclusión del archivo:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector
Nota: inclusión del archivo:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstdint
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\stdint.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\limits
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cfloat
Nota: inclusión del archivo:      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\float.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\climits
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cwchar
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstdio
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wstdio.h
Nota: inclusión del archivo:         C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
Nota: inclusión del archivo:      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\wchar.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_memcpy_s.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\errno.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_string.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wconio.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wctype.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wdirect.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wio.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_share.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wprocess.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wstring.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_wtime.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\sys/stat.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\sys/types.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\intrin0.h
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\intrin0.inl.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\isa_availability.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstddef
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstddef
Nota: inclusión del archivo:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xtr1common
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\initializer_list
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\new
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\exception
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\crtdbg.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_new_debug.h
Nota: inclusión del archivo:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_new.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\crtdefs.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\use_ansi.h
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\type_traits
Nota: inclusión del archivo:      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\malloc.h
Nota: inclusión del archivo:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_exception.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\eh.h
Nota: inclusión del archivo:        C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_terminate.hNota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xatomic.h
Nota: inclusión del archivo:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstring
Nota: inclusión del archivo:      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h
Nota: inclusión del archivo:       C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_memory.h
Nota: inclusión del archivo:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility
Nota: inclusión del archivo:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cassert
Nota: inclusión del archivo:   C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\assert.h
Nota: inclusión del archivo:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cmath
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(327): error C2065: 'HashTableCopy': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(327): error C2146: error de sintaxis: falta ';' delante del identificador 'hash_table'
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(327): error C3861: 'hash_table': no se encontró el identificador
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(360): error C2065: 'assert': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(360): error C2143: error de sintaxis: falta ';' delante de 'constante'
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(360): error C2014: el comando de preprocesador debe empezar con un primer espacio que no esté en blanco
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(361): error C2065: 'feature': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(432): error C2065: 'hash_table': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(449): error C2065: 'hash_table': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(460): error C2065: 'hash_table': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(468): error C2065: 'hash_table': identificador no declarado
C:\Users\group\Downloads\test_compil\crfasrnn_pytorch\crfasrnn\permutohedral.cpp(469): error C2065: 'hash_table': identificador no declarado
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py", line 1517, in _run_ninja_build
    subprocess.run(
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    cmdclass={'build_ext': cpp_extension.BuildExtension})
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py", line 635, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\group\anaconda3\envs\crfrnn\lib\site-packages\torch\utils\cpp_extension.py", line 1517, in _run_ninja_build
    subprocess.run(
RuntimeError: Error compiling objects for extension
```

I would be glad if you had some ideas to deal with this problem

Thanks in advance

**Comment by TrystanMayfaire** [comment]
I'm having the same problem. I would really like to use this code, but without building the permutohedral lattice code I cannot. I appreciate the time you've put into this, and look forward to getting this up and running!

**Comment by wangqiaoqiaoqiao** [comment]
I'm having the same problem.

**Comment by hdy6438** [comment]
I'm having the same problem.
